import { createTree } from "./tree.js";
import { prettyPrint, addOne, squared } from "./utils.js";

const myTree = createTree([5, 5, 4, 3, 2, 7, 7, 8, 4, 5, 1]);

myTree.insertNode(6);
myTree.insertNode(0);
myTree.insertNode(9);
myTree.insertNode(10);
myTree.deleteNode(6);
myTree.deleteNode(7);
console.log(myTree.root);
console.log(myTree.find(2));
console.log(myTree.find(12));
console.log(myTree.levelOrder(addOne));
console.log(myTree.preOrder(squared));
console.log(myTree.inOrder(squared));
console.log(myTree.postOrder(squared));
console.log(myTree.nodeHeight(8));
console.log(myTree.nodeDepth(2));
console.log(myTree.isBalanced());
myTree.deleteNode(1);
myTree.deleteNode(3);
myTree.deleteNode(0);
console.log(prettyPrint(myTree.getRoot()));
console.log(myTree.isBalanced());
console.log(myTree.getRoot());
console.log(myTree.rebalance());
console.log(myTree.getRoot());
console.log(prettyPrint(myTree.getRoot()));
console.log(myTree.isBalanced());
// console.log(myTree.root.data);
